### ISSUE TITLE
adopt ROS jenkins strategy

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_ci#10]
We shall adopt the ROS build and test strategy. In order to do so, we shall look at https://github.com/ros/rosdistro and create modified version of `generate_jenkins_devel` and similar scripts to create the jobs automatically. The script are here and need to be adapted for us: https://github.com/ros-infrastructure/jenkins_tools/tree/master/scripts

This will then also allow to trigger builds on the build farm. 

For this to work, we have to define our own distribution definition scripts: https://raw.githubusercontent.com/ros/rosdistro/master/hydro/distribution.yaml

**Comment by marc-hanheide** [comment]
Alternatively (and much less work for us) we can directly start submitting our packages to be integrated in ros distro: https://github.com/ros/rosdistro
Then they will also create ROS packages for us, but then we have top get rid of strange, specific CMAKE flags like for V4R (which we should in general). Opinions @cburbridge @hawesie @mzillich ?

**Comment by hawesie** [comment]
I guess the question is whether everything we do will go in to rosdistro and what we do with STRANDS-specific stuff that isn't generally interesting but we'd like to distribute anyway.

**Comment by marc-hanheide** [comment]
I had a closer look at the ros Jenkins infrastructure which has a lot of
paths hard coded to it but should still be fairly easy to adopt. Then we'd
actually have our own infrastructure, but using similar structures. The ros
Jenkins and build farm appears massively overworked and they can't keep up
well with the pull requests so we're likely better off hosting our own ppa
and Jenkins.

**Comment by hawesie** [comment]
Our own structure is good. I think we should submit some parts to the main structure too though. Please can you arrange a chat about this and other software issues do we can start getting cracking?

**Comment by marc-hanheide** [comment]
this is now done and dusted: https://github.com/strands-project/strands_management/wiki/STRANDS-Buildfarm-Administration
