### ISSUE TITLE
404 page not found error

### ISSUE THREAD

**Issue by OMARI1988** [strands-project/strands_ci#11]
Hi,

This gives a 404 page not found error, is this how I am supposed to update Lucie ? or should I update it manually from (Hydro Installation Instructions) ?

wget https://raw.github.com/strands-project/strands_ci/master/jenkins_tools/scripts/install_latest_jenkins_success.sh

Thanks,
Muhannad

**Comment by cdondrup** [comment]
I think this is very much outdated. Please just have a look at this: https://github.com/strands-project-releases/strands-releases/wiki#using-the-strands-repository
and install the metapackage afterwards: `sudo apt-get install ros-hydro-strands-robot`
