### ISSUE TITLE
MORSE hangs when started with fsmtest (stdout not read by Python tty process?)

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_ci#3]
The problem persists with fsmtest-0.11a. 

Although fsmtest runs through, the blender process (and probably others) hangs and has to be killed with SIGKILL. Here's the full log: https://gist.github.com/marc-hanheide/93439ac57e6d5ad009e9

see here: http://ascii.io/a/4589

**Comment by warp1337** [comment]
Hey Marc, thanks for the try :) Could you, somehow, start the setup on a different machine? I also started MORSE and a ROSCORE and and and..it worked using 0.11a, BTW, sorry I didn't increase the version number in the help. ups.

Additionally, if you start this configuration (you just need to 'sed' some paths, sorry for that) what happens?

[environment]
PATH=$PATH
MORSE_BLENDER=/media/FSM-Lab/releases/precise/x64/opt/blender/blender
MORSE_ROOT=/media/FSM-Lab/releases/precise/x64/

[component-1]
name = roscore
command = roscore
path = /opt/ros/groovy/bin/
execution_host = localhost
check_execution = True
check_type = pid,stdout 
timeout = 2,5
blocking = True,True
ongoing = True,False
criteria = ,started core service

[component-2]
name = morse_check
command = morse check
path = /media/FSM-Lab/releases/precise/x64/bin/
execution_host = localhost
check_execution = True
check_type = pid,stdout
timeout = 2,5
blocking = True,True
ongoing = False,False
criteria = ,Your environment is correctly setup to run MORSE

[component-3]
name = morse
command = morse run /media/FSM-Lab/releases/precise/x64/share/morse/examples/tutorials/tutorial-1-ros.py
path = /media/FSM-Lab/releases/precise/x64/bin/
execution_host = localhost
check_execution = True
check_type = pid,stdout
timeout = 2,10
blocking = True,True
ongoing = True,False
criteria = ,[SCENE INITIALIZED]

[component-4]
name = send_angles
command = sh /homes/flier/Projects/Ongoing/FSM-Testing/FSMtesting/tags/fsmtesting-0.11/configuration/morse/tools/morse-ros-atrv/sendangles.sh
path = /bin/
execution_host = localhost
check_execution = True
check_type = pid,stdout
timeout = 2,10
blocking = True,True
ongoing = True,False
criteria = ,Sending Data to ATRV

[component-5]
name = record_angles
command = sh /homes/flier/Projects/Ongoing/FSM-Testing/FSMtesting/tags/fsmtesting-0.11/configuration/morse/tools/morse-ros-atrv/recordangles.sh
path = /bin/
execution_host = localhost
check_execution = True
check_type = pid,stdout
timeout = 2,10
blocking = True,True
ongoing = True,False
criteria = ,Recording ARTV Angles

[component-6]
name = xeyes
command = xeyes
path = /usr/bin/
execution_host = localhost
check_execution = True
check_type = pid
timeout = 2
blocking = True
ongoing = False
criteria = 

[component-7]
name = blubb
command = ls /homes/flier
path = /bin/
execution_host = localhost
check_execution = True
check_type = pid
timeout = 2
blocking = True
ongoing = False
criteria = 

[run]
name = MORSE Test
namespace = http://my_namespace.com
run_order = ('roscore', 'morse_check', 'morse'),[('send_angles',), ('record_angles',)]
run_execution_duration = 5
result_assessment_order = ('blubb',),
result_assessment_execution_duration = 2

**Comment by marc-hanheide** [comment]
Can't test now, my _ongoing_ and _blocking_ differ from yours. Are mine wrong? Do mine work for you?

**Comment by marc-hanheide** [comment]
Check strands patrol.ini

**Comment by warp1337** [comment]
Just give it a little more time to come up, if that's what you are talking about.
Also I found this in the logs, not quite sure if that's a problem:

15:27:46 DEBUG [PTYbufferCleaner.py@38]: Writing: 'strands_sim.robots.scitosA5.Scitosa5: no interfaces available for this component! Check builder/data.py.
15:27:46 DEBUG [PTYbufferCleaner.py@38]: Writing: '
15:27:46 DEBUG [stdoutObserver.py@49]: morse:11704: reads: 'strands_sim.robots.scitosA5.Scitosa5: no interfaces available for this component! Check builder/data.py.
'

**Comment by warp1337** [comment]
Can I build your workspace as indicated in the wiki (catkin)?

**Comment by marc-hanheide** [comment]
The full instructions are in the strands_systems repository README.md. But that's quite an effort. I could also give you access to my machine if that helps. But not ATM. Those errors are not an issue. It works if I start morse outside fsmtest.

**Comment by warp1337** [comment]
Okay, first of all ty!...Interesting...it works outside of fsmt (annoying at the same time). Okay, I will dig into it, especially because this is the first time we encounter such a "show stopper". I will try to setup your infrastructure on my machine. I am currently working on 0.12, I thought the problem has been solved with 0.11a. I will keep you posted on this :dart:

**Comment by marc-hanheide** [comment]
Just tested, with your ongoing/blocking settings it works, but I don't understand why the other one blocks. There is still some bug there...

**Comment by marc-hanheide** [comment]
my more or less working config is in 1662a1577da51a720d373beca5dd6013e40cb763. 

But I'm pretty sure we have some nasty racing condition in there. In my 20 tests it worked 19 times. When run as another user with X forwarding (slower), then I only got it to run once. @warp1337 check your email for instructions to run it on my machine. There you should see the problem.

**Comment by warp1337** [comment]
I just got your infra. up and running. WOW - I like the way you bootstrap your system. Worked extremely well, congrats! :+1: Anyway, I can now reproduce the bug on my local machine, so there is (yet) no need to access the machine in Lincoln, ty anyhow.

Well, this bug really upsets me.

**Comment by warp1337** [comment]
Okay, I think am close to solving the problem. Here's the thing: morse and others are started in a script aka simulator.sh, fsmt actually checks the pid of the script _not_ the blender/morse executable. I am not quite sure (yet) why morse gets stuck, but if you give the PID _more_ time, let's say 5 seconds and set ongoing = true, it works like a charm. This is a hot fix for now. More later...

**Comment by warp1337** [comment]
Well, the main reason why all this didn't work is the "stdout observer" and the condition we chose. 
We set the success criteria to ",SCENE" which appears quite early in the start-up phase (and more than once). However, if you set it to "Exporting an image of capsize: (512, 512) pixels" which is the last output in case of a successful start, there is no problem at all. The explanation for this is rather simple, the SM switches to the next state after firing up morse, leaving morse in an undefined state. I assume this appears due to thread context switching in the PySCXML engine. It will take some time to clear this up, until then, if you use an stdout observer make sure you pick the right (final) string ;)

**Comment by marc-hanheide** [comment]
The problem is while there might be a "final" string for some processes, many will emit loads of log messages on stdout the whole time the run. Will that cause similar issues? I had the impression that also our nav_stack didn't proceed any further at some point. Of course that one will continuously issue log messages on stdout. And why is it a problem when the SM switches early? Shouldn't that then, if any, cause problems in the launching of the subsequent states (i.e. some data/stream not being present yet, not a problem in ROS generally though)? I don't know any details, but that one can end up in a undefined state doesn't sound good to me. I set the time to 5 secs in my experiments and even higher, but still had that occasional dead lock, I think (definitely at 5secs). I've checked, the PID exists ways earlier. So, I'm not convinced this is a final solution. Is there anything I can help with?

**Comment by warp1337** [comment]
No this is def. not final!! Just a "Hint". As I said, I am looking into it :) BTW: The patroller waypoints are not applied in MORSE even outside of fsmt...

" And why is it a problem when the SM switches early? Shouldn't that then, if any, cause problems in the launching of the subsequent states (i.e. some data/stream not being present yet, not a problem in ROS generally though)?"

Correct, one could implement checks (like morse check) to stop the SM if certain, i.e, topics are not avail. You can expect more from me during the next few days :dancers:

**Comment by marc-hanheide** [comment]
Cool, thanks for your great support on this. Let me know if I can be of any use.

**Comment by warp1337** [comment]
Please consider the new release 0.12
