### ISSUE TITLE
[fsmtest] environment variable DISPLAY not set for processes

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_ci#4]
My ini starts like this:

```
[environment]
#prefix = /vol/robocup/2013/
#release_prefix = /
#PKG_CONFIG_PATH = /usr/lib/pkgconfig
DISPLAY=:100
```

But still all processes are started on DISPLAY=:0. I suspect it's an issue of upper and lower case because in my scxml file I see this:

```
        <data id="environment">
            <variable val=":100" var="display" />
        </data>
```

**Comment by warp1337** [comment]
I see, this is a proper bug in the iniparser. Noted :) Hot-Fix: Export the variable before actually starting fsmt. All $vars in the shell are appended in the fsmt-env.

**Comment by warp1337** [comment]
Please consider the new release 0.12
