### ISSUE TITLE
[fsmtest] PID check always wait for "timeout"

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_ci#5]
If set to blocking and ongoing, execution will be delayed, even though the PID is there earlier, for the <timeout> seconds.

**Comment by warp1337** [comment]
Yes. I already noticed this behavior, I am currently re-implementing the "ongoing" feature the way we discussed it two (?) weeks ago.

**Comment by warp1337** [comment]
Please consider the new release 0.12
